# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gjman}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["NgTzeYang"]
  s.date = %q{2010-07-31}
  s.description = %q{
      Gjman is my neighbourhood friendly handyman with some useful tools.
      Tools available will remain diverse, and are added as and when i need them.
    }
  s.email = %q{ngty77@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "HISTORY.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ext/multivalent/Multivalent20060102.jar",
     "lib/ext/pdfc/CCLib.jar",
     "lib/ext/pdfc/CREDIT",
     "lib/ext/pdfc/PDFC.bat",
     "lib/ext/pdfc/PDFC.jar",
     "lib/ext/pdfc/PDFC.sh",
     "lib/ext/pdfc/PDFParser.jar",
     "lib/ext/pdfc/config.xml",
     "lib/ext/pdfc/license/LICENSE.log4j",
     "lib/ext/pdfc/license/lgpl-3.0.txt",
     "lib/ext/pdfc/license/overview.txt",
     "lib/ext/pdfc/log4j-1.2.15.jar",
     "lib/ext/pdfc/readme.txt",
     "lib/gjman.rb",
     "lib/gjman/file_system.rb",
     "lib/gjman/java_hacks/ForbidSystemExit$1.class",
     "lib/gjman/java_hacks/ForbidSystemExit$Exception.class",
     "lib/gjman/java_hacks/ForbidSystemExit.class",
     "lib/gjman/java_hacks/ForbidSystemExit.java",
     "lib/gjman/jruby.rb",
     "lib/gjman/pdf.rb",
     "lib/gjman/pdf/base.rb",
     "lib/gjman/pdf/compressor.rb",
     "lib/gjman/pdf/matcher.rb",
     "lib/gjman/pdf/merger.rb",
     "lib/gjman/pdf/utils.rb",
     "lib/gjman/pdf/utils/multivalent.rb",
     "lib/gjman/pdf/utils/pdfc.rb",
     "lib/gjman/rjb.rb",
     "spec/generic/file_system_spec.rb",
     "spec/generic/spec_helper.rb",
     "spec/pdf/compressor_spec.rb",
     "spec/pdf/data/compressed.pdf",
     "spec/pdf/data/merged_pages.pdf",
     "spec/pdf/data/page1.pdf",
     "spec/pdf/data/page2.pdf",
     "spec/pdf/data/page3.pdf",
     "spec/pdf/data/picture_x1.pdf",
     "spec/pdf/data/picture_x2.pdf",
     "spec/pdf/data/picture_x3_diff_pos.pdf",
     "spec/pdf/data/picture_x4_diff_size.pdf",
     "spec/pdf/data/picture_y1.pdf",
     "spec/pdf/data/text_x1.pdf",
     "spec/pdf/data/text_x2.pdf",
     "spec/pdf/data/text_y1.pdf",
     "spec/pdf/data/text_y2_diff_pos.pdf",
     "spec/pdf/data/text_y3_diff_size.pdf",
     "spec/pdf/data/text_y4_diff_font.pdf",
     "spec/pdf/data/text_y5_diff_style.pdf",
     "spec/pdf/data/text_y6_diff_color.pdf",
     "spec/pdf/data/text_y7_diff_bg.pdf",
     "spec/pdf/data/uncompressed.pdf",
     "spec/pdf/matcher_spec.rb",
     "spec/pdf/merger_spec.rb",
     "spec/pdf/spec_helper.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ngty/gjman}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Gjman is a handyman with some useful tools}
  s.test_files = [
    "spec/pdf/compressor_spec.rb",
     "spec/pdf/matcher_spec.rb",
     "spec/pdf/merger_spec.rb",
     "spec/pdf/spec_helper.rb",
     "spec/generic/file_system_spec.rb",
     "spec/generic/spec_helper.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bacon>, [">= 0"])
    else
      s.add_dependency(%q<bacon>, [">= 0"])
    end
  else
    s.add_dependency(%q<bacon>, [">= 0"])
  end
end

